export enum DaysEnum {
  MONDAY = 'MONDAY',
  TUESDAY = 'TUESDAY',
  WEDNESDAY = 'WEDNESDAY',
  THURSDAY = 'THURSDAY',
  FRIDAY = 'FRIDAY',
  SATURDAY = 'SATURDAY',
  SUNDAY = 'SUNDAY'
}

export enum DaysNumber {
  SUNDAY,
  MONDAY ,
  TUESDAY,
  WEDNESDAY ,
  THURSDAY,
  FRIDAY,
  SATURDAY
}